### ISSUE TITLE
Always use LF line endings

### ISSUE THREAD

**Issue by Sorokin-Anton** [serokell/nyan-interpolation#21]
# Clarification and motivation
Currently, if we have a CRLF-encoded source file with
```
a :: Text
a = [int||
p
q
|]
```
then `a = "p\r\nq\r\n"`, i.e. `int` uses the same line endings as the source file.

There are multiple reasons why we should use `\n` instead:

- In modern Haskell, the general agreement is to use `\n` as line separator when manipulating strings. E.g. `Prelude.unlines` and `Universum.unlines`, and `Fmt.fmtLn` are not creating `\r`s, and `lines "a\r\nb" = ["a\r","b"]`.  Also both `Prelude.readFile` and `Universum.readFile` are returning file content with forced LF endings.

- Instead of adding `\r`s during creating strings, [they are added during IO](https://hackage.haskell.org/package/base-4.17.0.0/docs/System-IO.html#g:25) (when code is runned on Windows). E.g. we can run
```
ghci> import Data.ByteString qualified as BS
ghci> writeFile "aaaa" "a\nb"
ghci> BS.readFile "aaaa"
"a\r\nb"
```
(ByteString's `readFile` is not stripping `\r`s)
But if we would write a string with `\r\n` (and `nyan-interpolation` is currently creating such strings), we would get a monster:
```
ghci> writeFile "aaaa" "a\r\nc"   
ghci> BS.readFile "aaaa"
"a\r\r\nc"
```
And this is displayed as a two lines break in vscode.

Also when a newline was escaped, a lonely `\r` appears, we should fix this too.

There is one reason to stay with `\r\n` : if someone wants to create a `ByteString` with those QuaiQuoters, then he would create a ByteString with LF endings, and write it to file using `BS.writeFile`, so he would obtain a file without `\r`'s. Maybe we should leave a switch for this.

Anyway, `\r\r\n` is much worse than `\n`

# Acceptance criteria
When a source file has CRLF endings, there still are no `\r`s in `int` result

**Comment by Martoon-00** [comment]
Good that this issue is discovered now...
